import type { Metadata } from "next";
import "./globals.css";
import { anekLatin } from "@/app/ui/font";
import { Toaster } from "@/components/ui/sonner";
import LoaderProvider from "@/hooks/LoaderProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* ye sari cheeze manifest aur icons ke liye */}
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#000000" />
        <link rel="apple-touch-icon" href="/icons/icon-192x192.png" />
        <link rel="icon" href="/icons/icon-192x192.png" />
      </head>
      <body
        className={`${anekLatin.className} antialiased min-h-screen `}
      >
        <LoaderProvider>
          <div className="text-white min-h-screen relative overflow-hidden bg-gradient-to-br from-gray-900 via-gray-800 to-black">
            {children}
            <Toaster position="top-right" richColors />
          </div>
        </LoaderProvider>
      </body>
    </html>
  );
}
